import argparse
import base64
import os
from xmlrpc import client
from groq import Groq
from langchain_groq import ChatGroq

client = Groq(api_key= "")
#llm = ChatGroq(groq_api_key = "", 
               #model_name = "meta-llama/llama-4-scout-17b-16e-instruct")

# Function to encode the image
def encode_image(image_url):
  print(image_url)
  if os.path.exists(image_url):
    with open(image_url, "rb") as image_file:
       return base64.b64encode(image_file.read()).decode('utf-8')
  else:
     print(f"Image file {image_url} does not exist.")
  

def analyze_image(image_url: str, question: str) -> str:
    """Generate a description or answer a question about the image.
    
    Args:
        image_url: URL of the image to analyze
        question: Question about the image
    Returns:
        str: Description or answer generated by the model.
    """
    image = encode_image(image_url)
    messages=[{"role": "user", 
              "content": [
                  {"type": "image_url", "image_url":{"url": f"data:image/jpeg;base64,{image}"}},
                  {"type": "text", "text": question}
                ]
              }]
    
    reply = client.chat.completions.create(messages = messages, model="meta-llama/llama-4-scout-17b-16e-instruct")
    return reply.choices[0].message.content
    #return llm.invoke(messages)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Image Description Generation with Groq LLM")
    parser.add_argument("image_url", type=str,  help="URL of the image to describe")
    parser.add_argument("question", type=str,  help="Question about the image")
    args = parser.parse_args()

    answer = analyze_image(args.image_url, args.question)
    print(answer)

    
#python .\multiModelLLM\imagesSample.py "C:/Users/Abhineet/Desktop/Kaushiki/begger1.PNG" "what is this?"


