import argparse
import base64
import os
from xmlrpc import client
from groq import Groq
from langchain_groq import ChatGroq

client = Groq(api_key= "")
#llm = ChatGroq(groq_api_key = "", 
               #model_name = "meta-llama/llama-4-scout-17b-16e-instruct")

# Function to encode the image
def encode_image(image_url):  
  if os.path.exists(image_url):
    with open(image_url, "rb") as image_file:
       return base64.b64encode(image_file.read()).decode('utf-8')
  else:
     print(f"Image file {image_url} does not exist.")
  

def analyze_image(image_url1: str, image_url2: str, question: str) -> str:
    """compare two images or answer a question about the images.
    
    Args:
        image_url1: URL of the first image to analyze
        image_url2: URL of the second image to analyze
        question: Question about the images
    Returns:
        str: compare in bullet point generated by the model.
    """
    image1 = encode_image(image_url1)
    image2 = encode_image(image_url2)
    messages=[{"role": "user", 
              "content": [
                  {"type": "image_url", "image_url":{"url": f"data:image/jpeg;base64,{image1}"}},
                  {"type": "image_url", "image_url":{"url": f"data:image/jpeg;base64,{image2}"}},
                  #{"type": "text", "text": question}
                ]
              }]
    
    reply = client.chat.completions.create(messages = messages, model="meta-llama/llama-4-scout-17b-16e-instruct")
    return reply.choices[0].message.content
    #return llm.invoke(messages)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Image comaprer with Groq LLM")
    parser.add_argument("image_url1", type=str,  help="URL of the first image to compare")
    parser.add_argument("image_url2", type=str,  help="URL of the second image to compare")
    args = parser.parse_args()

    while True:
        user_input = input("User: ")
        if user_input.lower() in ['quit', 'q']:
            print("Chat Ended")
            break
        answer = analyze_image(args.image_url1, args.image_url2, user_input)
        print(answer)

    

#python .\multiModelLLM\imageDiffFinder.py "C:\Users\Abhineet\ProjectSample\ChatbotUsingGroqLanggraph\multiModelLLM\kids1.JPG" "C:\Users\Abhineet\ProjectSample\ChatbotUsingGroqLanggraph\multiModelLLM\kids2.JPG"

