import argparse
from groq import Groq
import re
import sqlite3

client = Groq(api_key= "")

def create_prompt(db_structure, question):
    """Create input prompt for text to SQL conversion.
    
    Args:
        question: question to translate to SQL.
        
    Returns: 
        SQl query translating question.
    """
    parts=[]
    parts.append('Database:')
    #parts.append('create table Employee (ID int, Name varchar(255), Age int, Department varchar(255), Salary int);')
    parts.append(db_structure)
    parts.append('Translate this question to SQL')
    parts.append(question)
    return '\n'.join(parts)

def extract_structured_data(db_path):
    """Extract structured data from the database.
    
    Args:
        db_path: path to the sqlite database.
        db_structure: structure of the database.
    Returns:
        str: structured data extracted from the database.
    """
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT sql FROM sqlite_master WHERE type='table';")
        table_rows = cursor.fetchall()
        
        table_cells = [row[0] for row in table_rows]
        return '\n'.join(table_cells)

def process_query(dbPath, query):
    """Process the input query on SQLite DB.
    
    Args:
        dbPath: path to the sqlite database.
        query: input query string.
    Returns:
        str: query result as string
    """
    with sqlite3.connect(dbPath) as conn:
        cursor = conn.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()
        result = []
        row_str = [str(row) for row in rows]            
        return '\n'.join(row_str)

def call_llm(prompt):
    """Return answer generated by the llm.
    Args:
        prompt (str): prompts sent to llm
    Returns:
        str: answer generated by LLM."""
        
    messages = [{"role": "user", "content": prompt}]
    reply = client.chat.completions.create(messages = messages, model="meta-llama/llama-4-scout-17b-16e-instruct")
    return reply.choices[0].message.content


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Text to SQL Conversion with Groq LLM")
    #parser.add_argument("dbPath", type=str,  help="path to sqllite db")
    parser.add_argument("question", type=str,  help="Question to convert to SQL")
    args = parser.parse_args()
    
    db_Path = r"C:\Users\Abhineet\ProjectSample\ChatbotUsingGroqLanggraph\multiModelLLM\chinook\chinook.db"
    db_structure = extract_structured_data(db_Path)
    prompt = create_prompt(db_structure, args.question)  
    print("===Prompt to LLM:===")
    print(prompt) 

    raw_sql_query = call_llm(prompt)
    re_sql = r"```sql(.*?)```"
    sql_query = re.findall(re_sql, raw_sql_query, re.DOTALL)[0]
    print("===Generated SQL Query:===")
    print(sql_query)

    result = process_query(db_Path, sql_query)
    print("===Result:===")
    print(result)


#python .\multiModelLLM\sqlConverter.py "how many employee do we have?"